language: generic

env:
  global:
    - KODI_REPO_TRAVIS=https://api.travis-ci.org/repo/fopina%2FerDNA/requests

script:
  - pip freeze | grep requests
  #- .github/deploy.py

branches:
  only:
    - master
    - /^\d+\.\d+\.\d+$/

